---
- hosts: all
  become: yes
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install java-jre
      apt: name=default-jre

    - name: Install java-jdk
      apt: name=default-jdk

    - name: Extract hadoop
      unarchive:
        src: http://apache.rediris.es/hadoop/core/hadoop-2.9.1/hadoop-2.9.1.tar.gz
        dest: /home/vagrant/
        remote_src: yes

    - name: Export environment variables
      shell: export HADOOP_HOME=/home/vagrant/hadoop-2.9.1/ && export JAVA_HOME=/usr/lib/jvm//usr/lib/jvm/default-java/ && export PATH=$PATH:$HADOOP_HOME/bin:$JAVA_HOME/bin

    - name: Copy hosts
      copy:
        src: hosts.template
        dest: /tmp/hosts
    - name: Add hosts
      shell: cat /tmp/hosts >> /etc/hosts

    - name: Delete default route
      shell: ip route del default
    - name: Add default route
      shell: ip route add default dev eth1